# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-05 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('link', models.TextField()),
                ('category', models.TextField()),
                ('creator', models.TextField()),
                ('pubdate', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
    ]
